services:
  # ComfyUI Service (CPU-only for local development)
  comfyui:
    build:
      context: ./vps-comfyui
      dockerfile: Dockerfile
    container_name: comfy-ui-cpu
    ports:
      - "${COMFY_PORT:-8188}:${COMFY_PORT:-8188}"
    volumes:
      # Model and output persistence
      - ./vps-comfyui/models:/root/.cache/comfyui/ComfyUI/models:rw
      - ./vps-comfyui/outputs:/root/.cache/comfyui/ComfyUI/output:rw
      - ./vps-comfyui/custom_nodes/:/opt/ComfyUI/custom_nodes
    environment:
      - COMFYUI_DISABLE_CUDA=1
      - API_KEY=${API_KEY}
    restart: unless-stopped
    networks:
      - sd-network

  # Job Dispatcher Service
  dispatcher:
    image: python:3.10-slim
    container_name: sd-dispatcher
    ports:
      - "${DISPATCHER_PORT:-8187}:8187"
    volumes:
      - ./job-dispatcher:/app
      - ~/.config/gcloud:/root/.config/gcloud:ro
      - ~/.secrets/sa-key.json:/tmp/sa-key.json:ro
    working_dir: /app
    environment:
      - GCP_PROJECT=${GCP_PROJECT}
      - GCE_INSTANCE=${GCE_INSTANCE:-gpu-sd-worker}
      - GCE_ZONE=${GCE_ZONE:-us-central1-a}
      - JOB_BUCKET=${JOB_BUCKET:-gs://SD_JOBS}
      - OUT_BUCKET=${OUT_BUCKET:-gs://SD_OUTPUTS}
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/sa-key.json
    command: |
      sh -c "pip install -r requirements.txt 2>/dev/null || pip install fastapi uvicorn google-cloud-compute google-cloud-storage google-api-python-client && 
             uvicorn main:app --host 0.0.0.0 --port 8187"
    restart: unless-stopped
    networks:
      - sd-network

networks:
  sd-network:
    driver: bridge

volumes:
  comfyui_models:
    driver: local
  comfyui_outputs:
    driver: local
