version: "3.9"

services:
  dispatcher:
    image: python:3.10-slim # small base
    container_name: sd-dispatcher
    volumes:
      - ./dispatcher:/app # code lives here
      - ~/.config/gcloud:/root/.config/gcloud:ro # re-use host gcloud creds :contentReference[oaicite:2]{index=2}
    environment:
      - GCP_PROJECT=${GCP_PROJECT}
      - GCE_INSTANCE=gpu-sd-worker
      - GCE_ZONE=us-central1-a
      - JOB_BUCKET=gs://SD_JOBS
      - OUT_BUCKET=gs://SD_OUTPUTS
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    restart: unless-stopped
